---
title: "EDA"
author: "Riley Coburn"
date: "2023-02-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = F}
#always run

library(spotifyr)
library(lubridate)
library(tidyverse)
library(knitr)

Sys.setenv(SPOTIFY_CLIENT_ID = '4368c76bfce14f35b6ea1b3ea6b3723b')
Sys.setenv(SPOTIFY_CLIENT_SECRET = '533222a8cd3b4d8398d83e9c87ec084f')
access_token <- get_spotify_access_token()

setwd("~/Desktop/Denison/DA/DA 401/Project")

add_artist_to_albums <- function(artist_id) {
    albums <- get_artist_albums(artist_id) #getting all albums from the artist
    albums$artist_name <- get_artist(artist_id)$name #adding the artist name to the albums
    albums <- albums %>%
        select(artist_name, name, release_date, id) %>%
        dplyr::rename(album_name = name, album_id = id) 
    for(i in 1:nrow(albums)) { #for release dates with only the year, it sets it to be the first day of the year
    if(nchar(albums$release_date[i]) == 4) {
        albums$release_date[i] <- paste(albums$release_date[i], "-01-01", sep = "")
    }
    if(nchar(albums$release_date[i]) == 7) {
        albums$release_date[i] <- paste(albums$release_date[i], "-01", sep = "")
    }
}
    albums$year <- as.numeric(substr(albums$release_date, 1, 4))
    return(albums)
}

album_and_songs <- function(artist_id) {
    album_and_song <- cbind(add_artist_to_albums(artist_id)[1,], get_album(toString(add_artist_to_albums(artist_id)$album_id[1]))[[19]][[2]][,c("id", "name")], row.names=NULL)
    for(i in 2:nrow(add_artist_to_albums(artist_id))) {
        album_and_song <- rbind(album_and_song, cbind(add_artist_to_albums(artist_id)[i,], get_album(toString(add_artist_to_albums(artist_id)$album_id[i]))[[19]][[2]][,c("id", "name")], row.names=NULL))
    }
    album_and_song <- album_and_song %>%
        dplyr::rename(song_name = name, song_id = id)
    return(album_and_song)
}

fully_compiled <- function(artist_id) {
    albums <- album_and_songs(artist_id)
    sections <- get_track_audio_analysis(albums$song_id[1])$sections %>%
        rename(start_sections = start, duration_sections = duration)
    segments <- get_track_audio_analysis(albums$song_id[1])$segments[ , c(-7:-4)] %>%
        rename(start_segments = start, duration_segments = duration)
    audio_analysis <- merge(data.frame(sections, row.names=NULL), data.frame(segments, row.names=NULL), by = 0, all = TRUE)[-1]
    audio_analysis <- audio_analysis[order(audio_analysis$start_sections),] 
    complete <- cbind(albums[1,], audio_analysis, row.names=NULL) #changed to albums from album_and_songs(artist_id)
    for(i in 2:nrow(albums)) {
        sections <- get_track_audio_analysis(albums$song_id[i])$sections %>%
            rename(start_sections = start, duration_sections = duration)
        segments <- get_track_audio_analysis(albums$song_id[i])$segments[ , c(-7:-4)] %>%
            rename(start_segments = start, duration_segments = duration)
        audio_analysis <- merge(data.frame(sections, row.names=NULL), data.frame(segments, row.names=NULL), by = 0, all = TRUE)[-1]
        audio_analysis <- audio_analysis[order(audio_analysis$start_sections),]
        complete <- rbind(complete, cbind(albums[i,], audio_analysis, row.names=NULL))
    }
    return(complete)
}

get_genre_artists_list <- function(genre) {
    artists <- spotifyr::get_genre_artists(genre = genre, limit = 50) %>%
        select(name, id, genres) %>%
        rename(artist_id = id)
    artists$main_genre <- genre
    return(artists)
}

album_and_songs_genre <- function(genre) {
    artists <- get_genre_artists_list(genre)
    fully_complete <- album_and_songs(artists[1,]$artist_id)
    for(i in 2:nrow(artists)) {
        fully_complete <- rbind(fully_complete, album_and_songs(artists[i,]$artist_id))
    }
    return(fully_complete)
}

data_and_audio_sample <- function(data, sample_size) {
    rows <- sample(nrow(data), sample_size)
    tempo <- c()
    loudness <- c()
    for (i in 1:sample_size) {
        sections <- get_track_audio_analysis(data[rows[i],]$song_id)$sections
        segments <- get_track_audio_analysis(data[rows[i],]$song_id)$segments
        duration_percent <- (sections$tempo/sum(sections$tempo))
        tempo[i] <- weighted.mean(sections$tempo, duration_percent)
        loudness[i] <- weighted.mean(sections$loudness, duration_percent) 
    }
    sampled_data <- data.frame(data[sample(nrow(data), sample_size), ], tempo, loudness)
    row.names(sampled_data) <- NULL
    return(sampled_data)
}

"
make this a weighted average as well using the duration percent
fir = 0
for(i in 1:nrow(song1)) {
    fir = fir + song1$timbre[[i]][1]
}
fir/nrow(song1)
fir

song2 <- get_track_audio_analysis(rock[1,]$song_id)$segments

fir = 0
for(i in 1:nrow(song2)) {
    fir = fir + song2$timbre[[i]][1]
}
fir/nrow(song2)
fir

rock

song1
"

#for the second part of the project, use this code in the above function to give loudness, tempo, and average timbre for each of the 12 tibral vectors 
```

```{r}
set.seed(0)
gospel <- read.csv("gospel.csv")
rock <- read.csv("rock.csv")
post_punk <- read.csv("post-punk.csv")
polish <- read.csv("polish.csv")

rock_sam <- data_and_audio_sample(rock, 100)
for(i in 1:3) {
    rock_sam <- rbind(rock_sam, data_and_audio_sample(rock, 100))
}

rock_sam$genre <- rep("rock", 400)

gospel_sample <- data_and_audio_sample(gospel, 100)
gospel_sample$genre <- rep("gospel", 100)
rock_sample <- data_and_audio_sample(rock, 100)
rock_sample$genre <- rep("rock", 100)
post_punk_sample <- data_and_audio_sample(post_punk, 100)
post_punk_sample$genre <- rep("post-punk", 100)
polish_sample <- data_and_audio_sample(polish, 100)
polish_sample$genre <- rep("polish", 100)
small_data <- do.call(rbind, list(gospel_sample, rock_sample, post_punk_sample, polish_sample))
small_data$genre <- as.factor(small_data$genre)
small_data$rock <- ifelse(small_data$genre == "rock", 1, 0)

small_data_mod <- glm(factor(rock)~loudness+year+tempo, data = small_data, family = "binomial")
summary(small_data_mod)
small_data$probs = predict(small_data_mod, newdata=small_data, type="response")

plot(x = small_data$loudness, y = small_data$probs, col = factor(small_data$genre), main = "Predicted Probability of Rock Music by Song Loudness", xlab = "Loudness (dB)", ylab = "Precicted Probabilty of Rock")
legend(-37, 0.75, legend=unique(small_data$genre),
       col=factor(unique(small_data$genre)), pch=1, cex=0.8,
       title="Genres", text.font=4)

plot(x = small_data$tempo, y = small_data$probs, col = factor(small_data$genre), main = "Predicted Probability of Rock Music by Song Tempo", xlab = "Tempo (beats per minute)", ylab = "Precicted Probabilty of Rock")
legend(60, 0.75, legend=unique(small_data$genre),
       col=factor(unique(small_data$genre)), pch=1, cex=0.8,
       title="Genres", text.font=4)

plot(x = small_data$year, y = small_data$probs, col = factor(small_data$genre), main = "Predicted Probability of Rock Music by Release Year", xlab = "Year", ylab = "Precicted Probabilty of Rock")
legend(2015, 0.75, legend=unique(small_data$genre),
       col=factor(unique(small_data$genre)), pch=1, cex=0.8,
       title="Genres", text.font=4)
```

```{r}
bigger_data <- do.call(rbind, list(rock_sam, polish_sample, post_punk_sample, gospel_sample))
bigger_data$rock <- ifelse(bigger_data$genre == "rock", 1, 0)
bigger_data_mod <- glm(factor(rock)~loudness+year+tempo, data = bigger_data, family = "binomial")
summary(bigger_data_mod)
bigger_data$probs = predict(bigger_data_mod, newdata=bigger_data, type="response")

plot(x = bigger_data$loudness, y = bigger_data$probs, col = factor(bigger_data$genre), main = "Predicted Probability of Rock Music by Song Loudness", xlab = "Loudness (dB)", ylab = "Precicted Probabilty of Rock")
legend("topleft", legend=unique(bigger_data$genre),
       col=factor(unique(bigger_data$genre)), pch=1, cex=0.8,
       title="Genres", text.font=4)

plot(x = bigger_data$tempo, y = bigger_data$probs, col = factor(bigger_data$genre), main = "Predicted Probability of Rock Music by Song Tempo", xlab = "Tempo (beats per minute)", ylab = "Precicted Probabilty of Rock")
legend("topright", legend=unique(bigger_data$genre),
       col=factor(unique(bigger_data$genre)), pch=1, cex=0.8,
       title="Genres", text.font=4)

plot(x = bigger_data$year, y = bigger_data$probs, col = factor(bigger_data$genre), main = "Predicted Probability of Rock Music by Release Year", xlab = "Year", ylab = "Precicted Probabilty of Rock")
legend("topright", legend=unique(bigger_data$genre),
       col=factor(unique(bigger_data$genre)), pch=1, cex=0.8,
       title="Genres", text.font=4)

bigger_data$log_odds <- log(bigger_data$probs/(1-bigger_data$probs))

plot(x=bigger_data$loudness, y = bigger_data$log_odds)
plot(x=bigger_data$tempo, y = bigger_data$log_odds)

# minimize false negative rate
library(cutpointr)
library(ROCit)
cp1 <- cutpointr(data.frame(factor(bigger_data$rock),bigger_data$probs), x=bigger_data$probs, class = factor(bigger_data$rock), method = minimize_metric, metric = )

length(factor(bigger_data$rock))
length(bigger_data$probs)

summary(cp1)
plot_metric(cp1)
plot(cp1)

probs <- bigger_data$probs
rock_genre <- as.factor(bigger_data$rock)

cp <- cutpointr(str(data.frame(probs, rock_genre)), probs, rock_genre, method = maximize_metric, metric = sum_sens_spec, na.rm = T)

summary(cp)

str(data.frame(probs, rock_genre))

```

```{r}
post_punk
# timed it out for some reason... 
genres <- c("post-punk", "polish", "rap", "boy", "nerdcore", "dream", "crack", "columbus", "stl", "garage", "metal", "roots", "schlager", "italian", "military")

post_punk <- album_and_songs_genre(genres[3])

write.csv(post_punk, "~/Desktop/Denison/DA/DA 401/Project/rap.csv", row.names = F)

for(genre in genres) {
    genre_music <- album_and_songs_genre(genre)
    write.csv(genre_music, paste("~/Desktop/Denison/DA/DA 401/Project/", genre, ".csv", sep = ""), row.names = F)
}
```

